export * from './test';
export * from './base-page';
export * from './login-page';
export * from './inventory-page';
export * from './side-menu';
export * from './cart-page';
export * from './checkout-page-1';
export * from './checkout-page-2';
export * from './checkout-page-3';