name: REST API Playwright Tests
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run REST API tests
      run: npm run test:restapi
      env:
        BASE_URL_SAUCEDEMO: ${{ vars.BASE_URL_RESTAPI }}
        STORAGE_STATE_SAUCEDEMO: ${{ secrets.RESTAPI_KEY }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
